'use strict';

// Self-signed test CAs (EC P-256, 10 years) for the security-options tests:
// backend_tls_ca_pem / mtls_ca_pem fixtures. Generated once with openssl; no
// private key is included.

const CA_PEM = `-----BEGIN CERTIFICATE-----
MIIBvDCCAWOgAwIBAgIUbasCRKIhtkHhJiRZcsbyTemqrwowCgYIKoZIzj0EAwIw
NDEcMBoGA1UEAwwTR2F0ZUNvbnRyb2wgVGVzdCBDQTEUMBIGA1UECgwLc2Vjb3B0
LXRlc3QwHhcNMjYwOTEzMTQ0MTUwWhcNMzYwOTEwMTQ0MTUwWjA0MRwwGgYDVQQD
DBNHYXRlQ29udHJvbCBUZXN0IENBMRQwEgYDVQQKDAtzZWNvcHQtdGVzdDBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABBn9nNKmBaNGaO07hVJ6rfVEn5JYW4RnIfsR
/lBrPE3+wE9PEsJ+SJ3XCmKxRE3qlcWK2ayE14GVjvu8k3WgupKjUzBRMB0GA1Ud
DgQWBBT1ABtiMMe9x2BQCV9Acx8sCLoH3jAfBgNVHSMEGDAWgBT1ABtiMMe9x2BQ
CV9Acx8sCLoH3jAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0cAMEQCID5c
vzCo7cSiuBxPXdXDjT+Hr+YQVi/PaSTmJU93MJMOAiB5NO/dfRzxyM2k875J8W48
xU7FmfEfawyFN55kVcPX5A==
-----END CERTIFICATE-----
`;

const CA2_PEM = `-----BEGIN CERTIFICATE-----
MIIBwDCCAWegAwIBAgIUAbKu+YfVmJ4jeF8cAr3r+Zp8pwMwCgYIKoZIzj0EAwIw
NjEeMBwGA1UEAwwVR2F0ZUNvbnRyb2wgVGVzdCBDQSAyMRQwEgYDVQQKDAtzZWNv
cHQtdGVzdDAeFw0yNjA5MTMxNDQxNTFaFw0zNjA5MTAxNDQxNTFaMDYxHjAcBgNV
BAMMFUdhdGVDb250cm9sIFRlc3QgQ0EgMjEUMBIGA1UECgwLc2Vjb3B0LXRlc3Qw
WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARP6XYPI7dOMQl+sePQET7SxstidZAa
Ym8nw5Mua3vEalet4acw5HBYC4Ysz1ae7hLLJuHgL0uiMW3OYBjKR2dGo1MwUTAd
BgNVHQ4EFgQULKTbOeOSFBwYc0Fr0W85YhBc6IkwHwYDVR0jBBgwFoAULKTbOeOS
FBwYc0Fr0W85YhBc6IkwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNHADBE
AiAoiB1s9VtSTm44B9U7VKhMGwH+aGfU2/FSRW2wCkPHUwIgZ13mkP1lZghEYa8A
i8Uro14l0P3PTMNy0dqP1Xnu+k0=
-----END CERTIFICATE-----
`;

const BUNDLE_PEM = CA_PEM + CA2_PEM;

module.exports = { CA_PEM, CA2_PEM, BUNDLE_PEM };
