'use strict';

// ed25519 key pair for SFTP off-site targets, generated by GateControl
// (docs/feature-release-b.md §7) — node:crypto only, no ssh-keygen needed.
//
// Private key: unencrypted "openssh-key-v1" (the format ssh-keygen writes),
// stored encrypted in settings (backup.offsite.ssh_private_enc) so it travels
// with the JSON backup; materialised as a 0600 temp file only for the duration
// of one sftp call. Public key: "ssh-ed25519 AAAA… gatecontrol-backup".

const crypto = require('node:crypto');

const COMMENT = 'gatecontrol-backup';

function sshString(buf) {
  const b = Buffer.isBuffer(buf) ? buf : Buffer.from(buf, 'utf8');
  const len = Buffer.alloc(4);
  len.writeUInt32BE(b.length);
  return Buffer.concat([len, b]);
}

function u32(n) {
  const b = Buffer.alloc(4);
  b.writeUInt32BE(n >>> 0);
  return b;
}

/**
 * @returns {{ privateKey: string, publicKey: string }}
 *   privateKey: OpenSSH PEM ("-----BEGIN OPENSSH PRIVATE KEY-----")
 *   publicKey:  authorized_keys line
 */
function generate(comment = COMMENT) {
  const { publicKey, privateKey } = crypto.generateKeyPairSync('ed25519');
  const pub = Buffer.from(publicKey.export({ format: 'jwk' }).x, 'base64url');
  const seed = Buffer.from(privateKey.export({ format: 'jwk' }).d, 'base64url');
  if (pub.length !== 32 || seed.length !== 32) throw new Error('unexpected ed25519 key size');

  const pubBlob = Buffer.concat([sshString('ssh-ed25519'), sshString(pub)]);
  const check = crypto.randomBytes(4);
  let priv = Buffer.concat([
    check, check,
    sshString('ssh-ed25519'),
    sshString(pub),
    sshString(Buffer.concat([seed, pub])),
    sshString(comment),
  ]);
  const pad = [];
  for (let i = 1; (priv.length + pad.length) % 8 !== 0; i++) pad.push(i);
  priv = Buffer.concat([priv, Buffer.from(pad)]);

  const blob = Buffer.concat([
    Buffer.from('openssh-key-v1\0', 'binary'),
    sshString('none'),
    sshString('none'),
    sshString(''),
    u32(1),
    sshString(pubBlob),
    sshString(priv),
  ]);
  const b64 = blob.toString('base64').replace(/(.{70})/g, '$1\n').replace(/\n$/, '');
  return {
    privateKey: `-----BEGIN OPENSSH PRIVATE KEY-----\n${b64}\n-----END OPENSSH PRIVATE KEY-----\n`,
    publicKey: `ssh-ed25519 ${pubBlob.toString('base64')} ${comment}`,
  };
}

module.exports = { generate, COMMENT };
